require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'app/admin/*rb'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/SpaceAroundOperators:
  AllowForAlignment: true

RSpec/MultipleMemoizedHelpers:
  Enabled: false
